### ISSUE TITLE
How to run code in node js server?

### ISSUE THREAD

**Issue by bhaskarsaikia17** [Punit9464/Avon#2]
I not able to run code in node js server
Not in replit

**Comment by Punit9464** [comment]
First install all the dependencies and dev dependencies using `npm install`.

After that, create a index.js file in the main root directory with the codes as given below: 👇

```js
import { execSync } from "child_process";
execSync("npm run start");
```

That's it now save the file and hit the run button over your repl with node js.
Do check the .replit config file has the run command as `node index.js`

And you are done 👍

**Comment by bhaskarsaikia17** [comment]
Thanks a lot:))
