### ISSUE TITLE
Webhook Issue

### ISSUE THREAD

**Issue by Nightmary9992** [Punit9464/Avon#3]
https://i.imgur.com/mkhcwTG.png

**Comment by Punit9464** [comment]
Provide the webhook url to the config.ts file of config folder through which u wish to have the loggings of the commands

**Comment by Nightmary9992** [comment]
Can you send an Example?

**Comment by Punit9464** [comment]
![image](https://github.com/Punit9464/Avon/assets/80970599/ab5f7c55-e750-4882-ab8d-d78fcef009f0)
 just fill this.webhooks object and you will be freed from the errors due to unknown webhooks.
 put the webhook links there.

**Comment by Nightmary9992** [comment]
Which sort of links?
I've tried everything but nothing works, Can you send me an Example link?

**Comment by Punit9464** [comment]
Create a private channel in ur server. Then go to the settings of that channel , move to webhooks section and create one webhook there. Copy it's url and paste it in the config. 

If u didn't understand come here and mention me : https://discord.gg/lovezone. My global name: Punit.

**Comment by Nightmary9992** [comment]
It doesnt works
I've tried myself.

**Comment by Punit9464** [comment]
Mention me here : https://discord.gg/lovezone.

I will help u out

**Comment by Nightmary9992** [comment]
says, invalid invite

**Comment by Punit9464** [comment]
https://discord.gg/avonbot

this shall work fine.
