### ISSUE TITLE
Lavalink issue 

### ISSUE THREAD

**Issue by Ravan745** [Punit9464/Avon#4]
latest lavalink not working

**Comment by Punit9464** [comment]
These codes uses Shoukaku v3 which is compatible with version 3.x of Lavalink. So don't expect a miracle to happen using them with Lavalink v4.

**Comment by Ravan745** [comment]
Then I need to change it. 
It's not good; it's going to be an obstacle to my laziness.

**Comment by Punit9464** [comment]
Well u may update the codes for urself to Shoukaku v4 that is compatible with the latest lavalink version

**Comment by Ravan745** [comment]
yeh
